apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  initContainers:
    - name: init
      image: busybox:1.31.0
      command: ['touch test.txt']
      volumeMounts:
        - mountPath: /app
          name: app
  containers:
    - name: web
      image: web:1.0.1
      volumeMounts:
        - mountPath: /app
          name: app
  volumes:
    - name: app
      emptyDir: {}
