apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  initContainers:
    - name: init
      image: busybox:1.31.0
      volumeMounts:
        - mountPath: /app
          name: app
      command: ['touch /app/file.txt']
  containers:
    - name: web
      image: nginx
      volumeMounts:
        - mountPath: /app
          name: app
  volumes:
    - name: app
      emptyDir: {}
