apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcfornfs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeName: my-pv