apiVersion: v1
kind: Pod
metadata:
  name: pod-using-nfs
  namespace: volumes
spec:

  volumes:
    - name: nfs-volume
      nfs:
        server: 10.42.0.164
        path: /

  containers:
    - name: app
      image: alpine

      volumeMounts:
        - name: nfs-volume
          mountPath: /var/nfs

      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 5; done"]