apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: otus-volume
spec:
  containers:
  - name: install
    image: debian
    command:
      - wget
      - "-O"
      - "/mnt/index.html"
      - http://info.cern.ch
    volumeMounts:
    - name: local
      mountPath: "/mnt"
  volumes:
    - name: local
      persistentVolumeClaim:
        claimName: myclaim