apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: otus-volume
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  #
  initContainers:
    - name: install
      image: busybox:1.28
      command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - http://info.cern.ch
      volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
  volumes:
    - name: workdir
      persistentVolumeClaim:
        claimName: myclaim