apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: otus-volume
spec:
  containers:
  - name: install
    image: debian
    command: ["/bin/sh", "-c"]
    args:
      - echo "Welcome" >> /mnt/date.txt;
    volumeMounts:
    - name: local
      mountPath: "/mnt"
  volumes:
    - name: local
      persistentVolumeClaim:
        claimName: myclaim