apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: volumes
spec:
  nodeName: node3
  containers:
  - name: install
    image: debian
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /mnt/index.txt;
          sleep 10;
        done
    volumeMounts:
    - name: local
      mountPath: "/mnt"
  volumes:
    - name: local
      persistentVolumeClaim:
        claimName: myclaim