apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: otus-volume
spec:
  containers:
  - name: install
    image: busybox:1.28
    command:
      - wget
      - "-O"
      - "/local/index.html"
      - http://info.cern.ch
    volumeMounts:
    - name: /local
      mountPath: "/local"
  volumes:
    - name: /local
      persistentVolumeClaim:
        claimName: myclaim