apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: otus-volume
spec:
  containers:
  - name: install
    image: debian
    command: ["/bin/sh", "-c"]
    args:
      - x=1;
        while [ $x -le 5 ]; do
          echo "Welcome" >> /mnt/date.txt;
          x=$(( $x + 1 ));
        done

    volumeMounts:
    - name: local
      mountPath: "/mnt"
  volumes:
    - name: local
      persistentVolumeClaim:
        claimName: myclaim