apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec:
  volumes:
  - name: local
    persistentVolumeClaim:
      claimName: myclaim
  containers:
  - name: 1st
    image: nginx
    volumeMounts:
    - name: local
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: debian
    volumeMounts:
    - name: local
      mountPath: /local
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done