apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: otus-volume
spec:
  initContainers:
  - name: touch-file
    image: k8s.gcr.io/busybox
    command:
    - wget
    - "-O"
    - "/data/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: data
      mountPath: /data
  containers:
  - name: node-name
    image: k8s.gcr.io/busybox
    #command:
    #args:
    #  - ls
    volumeMounts:
      - name: data
        mountPath: /local
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: myclaim