apiVersion: v1
kind: Pod
metadata:
  name: pod_pv
  namespace: otus-volume
spec:
  initContainers:
  - name: touch-file
    image: k8s.gcr.io/busybox
    command: [ "sh", "-c" ]
    args:
      - touch "/data/$(hostname).$(date)"
    volumeMounts:
    - name: data
      mountPath: /data
  containers:
  - name: node-name
    image: k8s.gcr.io/busybox
    command: [ "sh", "-c" ]
    args:
    - while true; do
        echo -en '\n';
        date;
        ls /local;
        sleep 30;
        done;
    volumeMounts:
      - name: data
        mountPath: /local
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: myclaim