apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: nfs-pvc
    namespace: volumes
  nfs:
    path: /opt/nfs
    server: nfs-service
    readOnly: false