apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: volumes
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: local-path
  resources:
     requests:
       storage: 1Gi
  volumeName: my-pv