apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: volumes
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
     requests:
       storage: 1Gi
  storageClassName: local-path
  volumeName: my-pv