apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: otus-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: local-path