kind: Pod
apiVersion: v1
metadata:
  name: pod-using-nfs
spec:
  # Add the server as an NFS volume for the pod
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs

  # In this container, we'll mount the NFS volume
  # and write the date to a file inside it.
  containers:
    - name: app
      image: alpine
      # Mount the NFS volume in the container
      volumeMounts:
        ## name must match the volume name below
        - name: nfs
          mountPath: "/"

      # Write to a file inside our NFS
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /dates.txt; sleep 5; done"]